name: ci
on:
  push:
env:
  IMAGE_NAME: container-network-display
  OWNER_NAME: shwill
jobs:
  buildx:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Log in to registry
      #   run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build and push       
        uses: docker/build-push-action@v2          
        with:            
          context: .            
          file: ./Dockerfile            
          push: true                     
          tags: ghcr.io/$OWNER_NAME/$IMAGE_NAME:${{ steps.package-version.outputs.current-version}}, ghcr.io/$OWNER_NAME/$IMAGE_NAME:latest